# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HeadMain.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(954, 792)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 10, 841, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.gridLayoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 20, 31, 16))
        self.label.setObjectName("label")
        self.editHost = QtWidgets.QLineEdit(self.groupBox)
        self.editHost.setGeometry(QtCore.QRect(50, 20, 113, 20))
        self.editHost.setObjectName("editHost")
        self.editPort = QtWidgets.QLineEdit(self.groupBox)
        self.editPort.setGeometry(QtCore.QRect(210, 20, 41, 20))
        self.editPort.setObjectName("editPort")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(170, 20, 31, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(270, 20, 31, 16))
        self.label_3.setObjectName("label_3")
        self.editSID = QtWidgets.QLineEdit(self.groupBox)
        self.editSID.setGeometry(QtCore.QRect(300, 20, 91, 20))
        self.editSID.setObjectName("editSID")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(400, 20, 51, 20))
        self.label_4.setObjectName("label_4")
        self.editUser = QtWidgets.QLineEdit(self.groupBox)
        self.editUser.setGeometry(QtCore.QRect(450, 20, 113, 20))
        self.editUser.setObjectName("editUser")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(570, 20, 51, 20))
        self.label_5.setObjectName("label_5")
        self.editPassword = QtWidgets.QLineEdit(self.groupBox)
        self.editPassword.setGeometry(QtCore.QRect(610, 20, 113, 20))
        self.editPassword.setObjectName("editPassword")
        self.btnConnect = QtWidgets.QPushButton(self.groupBox)
        self.btnConnect.setGeometry(QtCore.QRect(740, 20, 75, 23))
        self.btnConnect.setObjectName("btnConnect")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 90, 281, 111))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushSearch = QtWidgets.QPushButton(self.groupBox_2)
        self.pushSearch.setGeometry(QtCore.QRect(190, 30, 75, 23))
        self.pushSearch.setObjectName("pushSearch")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(30, 30, 21, 20))
        self.label_6.setObjectName("label_6")
        self.lineEditSearch = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEditSearch.setGeometry(QtCore.QRect(60, 30, 113, 20))
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.checkBoxFullString = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxFullString.setGeometry(QtCore.QRect(70, 70, 71, 16))
        self.checkBoxFullString.setObjectName("checkBoxFullString")
        self.checkBoxAsColumn = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBoxAsColumn.setGeometry(QtCore.QRect(120, 70, 71, 16))
        self.checkBoxAsColumn.setObjectName("checkBoxAsColumn")
        self.horizontalLayout.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 954, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "数据库"))
        self.label.setText(_translate("MainWindow", "IP："))
        self.editHost.setText(_translate("MainWindow", "11.11.75.13"))
        self.editPort.setText(_translate("MainWindow", "1521"))
        self.label_2.setText(_translate("MainWindow", "端口："))
        self.label_3.setText(_translate("MainWindow", "SID："))
        self.editSID.setText(_translate("MainWindow", "gxbxorcl01"))
        self.label_4.setText(_translate("MainWindow", "用户名："))
        self.editUser.setText(_translate("MainWindow", "cwbase2_9999"))
        self.label_5.setText(_translate("MainWindow", "密码："))
        self.editPassword.setText(_translate("MainWindow", "gxtest8888"))
        self.btnConnect.setText(_translate("MainWindow", "连接"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.pushSearch.setText(_translate("MainWindow", "搜索"))
        self.label_6.setText(_translate("MainWindow", "表："))
        self.lineEditSearch.setText(_translate("MainWindow", "GXHSDYCONF"))
        self.checkBoxFullString.setText(_translate("MainWindow", "数据"))
        self.checkBoxAsColumn.setText(_translate("MainWindow", "行"))
